# Generated by Django 4.0.6 on 2022-08-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('revenue', models.CharField(max_length=225)),
                ('nonrevenue', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Costcentr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('under', models.CharField(max_length=225)),
                ('emply', models.CharField(max_length=225)),
            ],
        ),
    ]
