# Generated by Django 4.0.6 on 2022-08-25 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tally_app', '0002_costcategory_costcentr'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=225)),
                ('formal_name', models.CharField(max_length=225)),
                ('ISO_code', models.CharField(max_length=225)),
                ('decimal_places', models.CharField(default=2, max_length=225)),
                ('show_in_millions', models.CharField(max_length=225)),
                ('suffix_to_amount', models.CharField(max_length=225)),
                ('space_symbol_amount', models.CharField(max_length=225)),
                ('word_after_decimal', models.CharField(max_length=225)),
                ('decimal_no_in_words', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyAlter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slno', models.CharField(max_length=225)),
                ('currencys', models.CharField(max_length=225)),
                ('stdrate', models.CharField(max_length=225)),
                ('lastvrate', models.CharField(max_length=225)),
                ('specirate', models.CharField(max_length=225)),
                ('lastvrate2', models.CharField(max_length=225)),
                ('specirate2', models.CharField(max_length=225)),
                ('cname', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tally_app.createcurrency')),
            ],
        ),
    ]
